apiVersion: v1
kind: Service
metadata:
  name: sidecar-svc
  labels:
    app: sidecar
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30002
      protocol: TCP
  selector:
    app: sidecar
