apiVersion: v1
kind: ConfigMap
metadata:
  name: mongod-config
data:
  config.yaml: |
    storage:
      dbPath: "/data/db"
    systemLog:
      path: "/data/db/logs/mongod.log"
      destination: "file"
      logAppend: true
    security:
      authorization: "enabled"
      
      
