apiVersion: v1
kind: Pod
metadata:
  name: mongo-client
spec:
  containers:
    - image: mongo
      name: mongo-client
#      env:
#        - name: mongo-client_INITDB_ROOT_USERNAME
#          value: 'dummy'
#        - name: mongo-client_INITDB_ROOT_PASSWORD
#          value: 'dummy'
#