apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: auth-binding
  namespace: auth

subjects:
  - kind: ServiceAccount
    name: auth-sa
    namespace: auth

roleRef:
  kind: Role
  name: auth-view
  apiGroup: rbac.authorization.k8s.io