apiVersion: ratelimit.shalabi.com/v1
kind: DefaultControllerRateLimiter
metadata:
  labels:
    app.kubernetes.io/name: defaultcontrollerratelimiter
    app.kubernetes.io/instance: defaultcontrollerratelimiter-sample
    app.kubernetes.io/part-of: ratelimit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ratelimit
  name: defaultcontrollerratelimiter-sample
spec:
  # TODO(user): Add fields here
