apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cuss.complex.learn.com
spec:
  group: complex.learn.com
  names:
    kind: Customer
    listKind: CustomerList
    plural: cuss
    singular: cus
  scope: Namespaced

  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                custometrId:
                  type: integer
                accountValue:
                  type: number
                name:
                  type: string
                active:
                  type: boolean
                address:
                  type: object
                  properties:
                    name:
                      type: string
                    street:
                      type: string
                    city:
                      type: string
                    zip:
                      type: string
                contacts:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string