apiVersion: v1
kind: PersistentVolume
metadata:
  name: slave-delay-logs-pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /logs