apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: opsmanager
#  namespace: mongodb-operator
spec:
  replicas: 1
  version: 5.0.0
  adminCredentials: ops-manager-admin-secret
  externalConnectivity:
    type: LoadBalancer
  applicationDatabase:
    members: 3
    version: 5.0.5-ent

