apiVersion: v1
kind: Pod
metadata:
  name: arbiter
  labels:
    app: arbiter
spec:
#  initContainers:
#    - name: init-myservice
#      image: busybox:1.28
#      command: [ 'sh', '-c', "chmod 400 /etc/security/keyfile && chown 999:999 /etc/security/keyfile && cp /etc/security/keyfile /etc/keyfile" ]
#      volumeMounts:
#      - name: keyfile
#        mountPath: "/etc/security"
#  #      readOnly: true
  containers:
    - image: mongo
      name: mongo
      args: ["--config","/conf/config.yaml"]
      livenessProbe:
        exec:
          command:
            - mongo
            - --disableImplicitSessions
            - --port
            - "27004"
            - --eval
            - "db.adminCommand('ping')"
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 6
      readinessProbe:
        exec:
          command:
            - mongo
            - --disableImplicitSessions
            - --port
            - "27004"
            - --eval
            - "db.adminCommand('ping')"
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 6
      volumeMounts:
        - name: "mongo-data-dir"
          mountPath: "/data/db"
        - name: "mongo-logs-dir"
          mountPath: "/logs"
        - name: conf
          mountPath: "/conf"
#        - name: keyfile
#          mountPath: "/etc/security"
         # readOnly: true
#      env:
#        - name: MONGO_INITDB_ROOT_USERNAME
#          valueFrom:
#            secretKeyRef:
#              name: mongo-creds
#              key: username
#        - name: MONGO_INITDB_ROOT_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: mongo-creds
#              key: password
  nodeSelector:
    replica: arbiter
  volumes:
    - name: "mongo-data-dir"
      persistentVolumeClaim:
        claimName: "arbiter-data"
    - name: "mongo-logs-dir"
      persistentVolumeClaim:
        claimName: "arbiter-logs"
        readOnly: false
    - name: conf
      configMap:
        name: arbiter-config
        items:
          - key: config.yaml
            path: config.yaml
#    - name: keyfile
#      configMap:
#        name: keyfile
#        #defaultMode: 0400
#        items:
#          - key: keyfile
#            path: keyfile