apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: printers.additional.printer.columns.com
spec:
  group: additional.printer.columns.com
  scope: Namespaced
  names:
    plural: printers
    singular: printer
    kind: AdditionalPrinterColumns
    shortNames:
      - apc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
      additionalPrinterColumns:
        - name: Spec
          type: string
          description: The cron spec defining the interval a CronJob is run
          jsonPath: .spec.cronSpec
        - name: Replicas
          priority: 2
          type: integer
          description: The number of jobs launched by the CronJob
          jsonPath: .spec.replicas
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp