apiVersion: v1
kind: Pod
metadata:
  name: ks-demo-pod
spec:
  serviceAccountName: pods-service
  containers:
    - name: shell
      image: alpine:3.7
      command:
        - "sh"
        - "-c"
        - "sleep 10000"
