apiVersion: v1
kind: Service
metadata:
  name: todolist-service
spec:
  selector:
    app: todolist
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
      annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8080"
    spec:
      containers:
        - name: todolist
          image: shalabi67/devopsmon-app
          ports:
            - containerPort: 8080
