apiVersion: v1
kind: Pod
metadata:
  name: cm-test-pod
spec:
  containers:
    - name: cm-test-pod
      image: cirros
      command: ["/bin/sh", "-c", "env | grep VAR"]
      envFrom:
        - configMapRef:
            name: variables.yaml
