apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-demo-deploy
  namespace: policy-demo

spec:
  replicas: 2
  selector:
    matchLabels:
      app: policy-demo
      run: nginx

  # Pod specification
  template:
    metadata:
      labels:
        app: policy-demo
        run: nginx
    spec:

      # containers specification
      containers:
        - name: hello-pod
          image: nginx
           # imagePullPolicy: Always    #use with production this will be more secure
          ports:
            - containerPort: 80
