apiVersion: v1
kind: Service
metadata:
  name: nginx # policy-demo-svc
  namespace: policy-demo
  labels:
    run: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    run: nginx
