apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      # the pod is eligible to run on node N if node N has a label with key topology.kubernetes.io/zone and some value V
      # such that there is at least one node in the cluster with key topology.kubernetes.io/zone and value V that is
      # running a pod that has a label with key "security" and value "S1".
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: security
                operator: In
                values:
                  - S1
          topologyKey: failure-domain.beta.kubernetes.io/zone
    podAntiAffinity:
      # The pod anti-affinity rule says that the pod should not be scheduled onto a node if that node is in the same
      # zone as a pod with label having key "security" and value "S2"
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: security
                  operator: In
                  values:
                    - S2
            topologyKey: failure-domain.beta.kubernetes.io/zone
  containers:
    - name: with-pod-affinity
      image: k8s.gcr.io/pause:2.0
