apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 10
  minReadySeconds: 10
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  # Pod specification
  template:
    metadata:
      labels:
        app: hello-world
    spec:

      # containers specification
      containers:
        - name: hello-pod
          image: nigelpoulton/pluralsight-docker-ci:latest
           # imagePullPolicy: Always    #use with production this will be more secure
          ports:
            - containerPort: 8080
