apiVersion: learn.shalabi.com/v1
kind: Server
metadata:
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server-sample
    app.kubernetes.io/part-of: informers
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: informers
  name: server-sample
spec:
  # TODO(user): Add fields here
