# Example shows how to use hostPath
apiVersion: v1
kind: Pod 
metadata:
  name: docker-volume
spec: 
  containers: 
  - name: docker 
    image: docker 
    command: ["sleep"] 
    args: ["100000"]
    volumeMounts: 
    - name: docker-socket 
      mountPath: /var/run/docker.sock 
    resources:
  volumes: 
  - name: docker-socket
    # this volume will allow container to run docker commands
    hostPath:
      path: /var/run/docker.sock
      type: Socket

# Once Pod is created you can shell into it to run Docker commands:
# kubectl exec [pod-name] -it sh
# docker ps
