apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: testing
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: nginx-pod-port
      protocol: TCP
      name: web
  selector:
    app: nginx

