apiVersion: v1
kind: Service
metadata:
  name: nginx-ns
  labels:
    app: nginx
spec:
  type: ExternalName
  externalName: nginx.testing.svc.cluster.local
  ports:
    - port: 80
      targetPort: nginx-pod-port
      protocol: TCP
      name: web
  selector:
    app: nginx

