---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ratelimit.shalabi.com
  resources:
  - defaultcontrollerratelimiters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ratelimit.shalabi.com
  resources:
  - defaultcontrollerratelimiters/finalizers
  verbs:
  - update
- apiGroups:
  - ratelimit.shalabi.com
  resources:
  - defaultcontrollerratelimiters/status
  verbs:
  - get
  - patch
  - update
