# permissions for end users to view roarapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: roarapp-viewer-role
rules:
- apiGroups:
  - roarapp.roarapp.com
  resources:
  - roarapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - roarapp.roarapp.com
  resources:
  - roarapps/status
  verbs:
  - get
