apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ats.cnat.programming-kubernetes.info
spec:
  group: cnat.programming-kubernetes.info
  names:
    kind: At
    listKind: AtList
    plural: ats
    singular: at
  scope: Namespaced

  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schedule:
                  type: string
                command:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string

      subresources:
        status: {}

      additionalPrinterColumns: #(optional)
        - name: schedule
          type: string
          jsonPath: .spec.schedule
        - name: command
          type: string
          jsonPath: .spec.command
          priority: 1  # show only in the side view
        - name: phase
          type: string
          jsonPath: .status.phase