# permissions for end users to edit wbcsnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wbcsnapshot-editor-role
rules:
- apiGroups:
  - snapshot.wbc.com
  resources:
  - wbcsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - snapshot.wbc.com
  resources:
  - wbcsnapshots/status
  verbs:
  - get
