# permissions for end users to view wbcsnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wbcsnapshot-viewer-role
rules:
- apiGroups:
  - snapshot.wbc.com
  resources:
  - wbcsnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.wbc.com
  resources:
  - wbcsnapshots/status
  verbs:
  - get
