apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/mshalabai/learn/LearnKubernetes/mongodb/data/mongo
        containerPath: /data