apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-example1-1
  labels:
    app: web
spec:
  affinity:
    # The pod anti-affinity rule says that no two web pods should be scheduled together on the specific zone.
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - web
          topologyKey: topology.kubernetes.io/zone
  containers:
    - name: with-pod-affinity
      image: nginx
