apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: statuses.subresource.com
spec:
  group: subresource.com
  scope: Namespaced
  names:
    plural: statuses
    singular: status
    kind: StatusSubresource
    shortNames:
      - ssub
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
            status:
              type: object
              properties:
                phase:
                  type: string
      subresources:
        # status enables the status subresource.
        status: {}
      additionalPrinterColumns:
        - name: Spec
          type: string
          description: The cron spec defining the interval a CronJob is run
          jsonPath: .spec.cronSpec
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Version
          type: string
          jsonPath: .metadata.resourceVersion
        - name: Replicas
          priority: 2
          type: integer
          description: The number of jobs launched by the CronJob
          jsonPath: .spec.replicas
