apiVersion: v1
kind: Pod
metadata:
  name: hdd-pod
  labels:
    env: prod
spec:
  containers:
    - name: frontend
      image: nginx:alpine
      imagePullPolicy: IfNotPresent

  # This pad will run on a node with disktype=hdd
  nodeSelector:
    disktype: hdd
